name: londonmapbot

on:
  schedule:
    - cron: '14 9/8 * * *'  # trigger at 09:14 and 17:14 every day

jobs:
  post-image:
    runs-on: macOS-latest
    env:
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_DEFAULT_TOKEN}}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: Rscript -e 'install.packages(c("rtoot", "rtweet", "purrr"), dependencies = TRUE)'
      - name: Create and post image
        run: Rscript post-image.R
